/*
 * LCD_Controller.c
 *
 *  Created on: 1 Apr 2023
 *      Author: Hassan
 */
#include "LCD_Controller.h"
LCD_Config_t LCD0;
LCD_Config_t LCD1;

void (* LCD1_Status)();
void LCD_Welcome(void)
{

	LCD_WRITE_COMMAND(LCD1_INDEX, LCD_DISP_ON);
	LCD_WRITE_COMMAND(LCD1_INDEX, LCD_CLEAR_SCREEN);
	LCD_GOTO_XY(LCD1_INDEX, 0, 0);
	LCD_WRITE_STRING(LCD1_INDEX,"Welcome in Smart Parking");
	LCD1_Status=LCD_Idle;
}

void LCD_Display_Empty_Slots(void)
{
	LCD_WRITE_COMMAND(LCD1_INDEX, LCD_DISP_ON);
	LCD_WRITE_COMMAND(LCD1_INDEX, LCD_CLEAR_SCREEN);
	LCD_GOTO_XY(LCD1_INDEX, 0, 0);
	LCD_WRITE_STRING(LCD1_INDEX,"Empty Slots=");
	LCD_GOTO_XY(LCD1_INDEX, 13, 0);
	LCD_WRITE_CHAR(LCD1_INDEX,Available_Slots+48);
	LCD1_Status=LCD_Idle;
}
void LCD_Full_Parking(){
	LCD_WRITE_COMMAND(LCD1_INDEX, LCD_DISP_ON);
	LCD_WRITE_COMMAND(LCD1_INDEX, LCD_CLEAR_SCREEN);
	LCD_GOTO_XY(LCD1_INDEX, 0, 0);
	LCD_WRITE_STRING(LCD1_INDEX,"Parking is Full");
}
void LCD_Farewell(){
	LCD_WRITE_COMMAND(LCD1_INDEX, LCD_DISP_ON);
	LCD_WRITE_COMMAND(LCD1_INDEX, LCD_CLEAR_SCREEN);
	LCD_GOTO_XY(LCD1_INDEX, 0, 0);
	LCD_WRITE_STRING(LCD1_INDEX,"See You");
}
void LCD_Idle(){
	LCD1_Status=LCD_Idle;
}
void LCD_Rejected(){
	LCD_WRITE_COMMAND(LCD1_INDEX, LCD_DISP_ON);
	LCD_WRITE_COMMAND(LCD1_INDEX, LCD_CLEAR_SCREEN);
	LCD_GOTO_XY(LCD1_INDEX, 0, 0);
	LCD_WRITE_STRING(LCD1_INDEX,"Not Allowed ID");
	LCD1_Status=LCD_Display_Empty_Slots;

}
void LCDS_init(){
	LCD1.LCD_MODE=LCD_MODE_4BIT_2LINES;
	LCD1.EN_LCD_PIN.GPIO_Port = GPIOA;
	LCD1.EN_LCD_PIN.GPIO_PIN = GPIO_Pin_6;
	LCD1.RS_LCD_PIN.GPIO_Port = GPIOA;
	LCD1.RS_LCD_PIN.GPIO_PIN = GPIO_Pin_5;
	LCD1.RW_LCD_PIN.GPIO_Port = GPIOA;
	LCD1.RW_LCD_PIN.GPIO_PIN = GPIO_Pin_4;
	LCD1.D_LCD_PIN[0].GPIO_Port = GPIOA;
	LCD1.D_LCD_PIN[0].GPIO_PIN = GPIO_Pin_12;
	LCD1.D_LCD_PIN[1].GPIO_Port = GPIOA;
	LCD1.D_LCD_PIN[1].GPIO_PIN = GPIO_Pin_13;
	LCD1.D_LCD_PIN[2].GPIO_Port = GPIOA;
	LCD1.D_LCD_PIN[2].GPIO_PIN = GPIO_Pin_14;
	LCD1.D_LCD_PIN[3].GPIO_Port = GPIOA;
	LCD1.D_LCD_PIN[3].GPIO_PIN = GPIO_Pin_15;


	LCD0.LCD_MODE=LCD_MODE_4BIT_2LINES;
	LCD0.EN_LCD_PIN.GPIO_Port = GPIOB;
	LCD0.EN_LCD_PIN.GPIO_PIN = GPIO_Pin_10;
	LCD0.RS_LCD_PIN.GPIO_Port = GPIOB;
	LCD0.RS_LCD_PIN.GPIO_PIN = GPIO_Pin_11;
	LCD0.RW_LCD_PIN.GPIO_Port = GPIOA;
	LCD0.RW_LCD_PIN.GPIO_PIN = GPIO_Pin_4;
	LCD0.D_LCD_PIN[0].GPIO_Port = GPIOB;
	LCD0.D_LCD_PIN[0].GPIO_PIN = GPIO_Pin_12;
	LCD0.D_LCD_PIN[1].GPIO_Port = GPIOB;
	LCD0.D_LCD_PIN[1].GPIO_PIN = GPIO_Pin_13;
	LCD0.D_LCD_PIN[2].GPIO_Port = GPIOB;
	LCD0.D_LCD_PIN[2].GPIO_PIN = GPIO_Pin_14;
	LCD0.D_LCD_PIN[3].GPIO_Port = GPIOB;
	LCD0.D_LCD_PIN[3].GPIO_PIN = GPIO_Pin_15;

	LCD_INIT(0, &LCD0);
	LCD_INIT(1, &LCD1);
}
