/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Hassan Abd Eltawab
 ******************************************************************************
*/


#include"Stm32_F103C6_gpio_driver.h"
#include"Stm32_F103C6_UART_driver.h"
#include"Stm32_F103C6_SPI_driver.h"
typedef volatile unsigned int vuint32_t;
#include<stdio.h>
#include <lcd.h>
#include"keypad.h"
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
//#define MCU_Act_As_Master
#define MCU_Act_As_Slave

void clock_init()
{
	RCC_GPIOA_CLK_EN();  // Enable GPIOA Clock
	RCC_GPIOB_CLK_EN();   //Enable GPIOB Clock
	RCC_AFIO_CLK_EN();
}
uint16_t ch;
void SPI_Interrupt_Call_Back(struct S_IRQ_SRC irq_src)
{
#ifdef MCU_Act_As_Slave
	if(irq_src.RXNE)
	{
		ch=0xf;
		MCAL_SPI_Tx_Rx(SPI1, &ch, Disabled);
		MCAL_USART_Send(USART1, &ch, Enable);
	}
#endif
}
void Uart_CallBack(void)
{

#ifdef MCU_Act_As_Master
	MCAL_USART_Recieve(USART1, &ch, Disable);
	MCAL_USART_Send(USART1, &ch, Enable);
	//Write zero to send data
	//manually reset PA4 to work as slave select and enable the transmission

	MCAL_GPIO_WritePin(GPIOA, GPIO_Pin_4, GPIO_PIN_RESET);
	MCAL_SPI_Tx_Rx(SPI1, &ch, Enabled);
	MCAL_GPIO_WritePin(GPIOA, GPIO_Pin_4, GPIO_PIN_SET);
#endif

}

int main(void)
{
	UART_Config_t CFG;
	clock_init();
	CFG.BaudRate = USART_BaudRate_115200;
	CFG.HWFlowCtl = USART_HwFlowCtl_NONE;
	CFG.IRQ_Enable = USART_IRQ_Enable_RXIEN;
	CFG.Parity = USART_Parity_None;
	CFG.Payload_Length = USART_Payload_Length8;
	CFG.StopBits = USART_StopBits_1;
	CFG.USART_Mode = USART_MODE_TX_RX;
	CFG.P_IRQ_CallBack = Uart_CallBack;
	MCAL_USART_Init(&CFG,USART1);
	MCAL_USART_SetPins(USART1);

	//===============================SPI============================//
	SPI_Config_t SPICfg;
	SPICfg.CLock_Phase = SPI_Clock_Polarity_High_idel;
	SPICfg.CLock_Polarity =SPI_Clock_Phase_Trailing;
	SPICfg.Frame_Format = SPI_Frame_Format_MSB_1st;
	SPICfg.Pay_Load_Length = SPI_Pay_Load_Length_8bit;
	SPICfg.SPI_Prescaler = SPI_Divide_Prescaler_8;
	SPICfg.Communication_Mode = SPI_Direction_2lines;

#ifdef MCU_Act_As_Master
	SPICfg.Device_Mode = SPI_Mode_Master;
	SPICfg.IRQ_Enable =  SPI_IRQ_Enable_Non;
	SPICfg.NSS = SPI_NSS_Internal_Soft_Set;
	SPICfg.P_IRQ_CallBack = NULL;

	//Manually operate PA4 as SS and set idle state to 1
	GPIO_PinConfig_t P_Config;
	P_Config.GPIO_Pin_Number = GPIO_Pin_4;
	P_Config.GPIO_Mode = GPIO_MODE_OUTPUT_PP_10M;
	MCAL_GPIO_Init(GPIOA, &P_Config);
	//Write one
	MCAL_GPIO_WritePin(GPIOA, GPIO_Pin_4, GPIO_PIN_SET);
#endif
#ifdef MCU_Act_As_Slave
	SPICfg.Device_Mode = SPI_Mode_Slave;
	SPICfg.IRQ_Enable  = SPI_IRQ_Enable_RXNE;
	SPICfg.NSS = SPI_NSS_Hard_Slave;
	SPICfg.P_IRQ_CallBack = SPI_Interrupt_Call_Back;
#endif
	MCAL_SPI_Init(SPI1, &SPICfg);
	MCAL_SPI_GPIO_Set_Pins(SPI1);
	while (1)
	{

	}
}
